version: '2'
services:
    mssql:
        build:
            context: ./
            dockerfile: deploy/mssql.docker
        ports:
            - "14331:1433"
        environment:
            SA_PASSWORD: "Cnap01Cnap01"
            ACCEPT_EULA: "Y"
        # links:
        #     - test
        volumes:
            - ./:/var/www/
    sqlsrv:
        build:
            context: ./
            dockerfile: deploy/sqlsrv.docker
        volumes:
            - ./:/var/www/
        ports:
            - "8080:80"
        links:
            - mssql
